name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \ test
               -d '{"content": "🚀 New push to main branch!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
