name: Notify Discord

on:
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"username":"GitHub Bot","content":"🚀 A new push was made to `main`!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
