name: Notify Discord

on:
  workflow_dispatch:

jobs:
  send_discord_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "**In-Training VAs (1 Month)**\n```\nProduct Research\nInitial payment: $349 ($174.50 upfront to begin).\nWeeks 1 & 2: Free service.\nWeek 3: $96/week (24hr part-time) or $160/week (40hr full-time), continuing until canceled.\nWeek 4: Weekly rate + remaining $174.50 initial fee.\n\nFull Account Management\nInitial payment: $349 ($174.50 upfront to begin).\nWeeks 1 & 2: Free service.\nWeek 3: $144/week (24hr part-time) or $480/week (40hr full-time), continuing until canceled.\nWeek 4: Weekly rate + remaining $174.50 initial fee.\n\nBookkeeping\nInitial payment: $349 ($174.50 upfront to begin).\nWeeks 1 & 2: Free service.\nWeek 3: $96/week (24hr part-time) or $160/week (40hr full-time), continuing until canceled.\nWeek 4: Weekly rate + remaining $174.50 initial fee.\n```"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
