name: Send Discord Pricing Sections

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Product Research section
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "title": "📦 In-Training VAs: Product Research",
                "description": "Initial payment: **$349** ($174.50 upfront to begin).\n\n**Weeks 1 & 2:** Free service.\n**Week 3:** $96/week (24hr part-time) or $160/week (40hr full-time), continuing until canceled.\n**Week 4:** Weekly rate + remaining $174.50 initial fee.",
                "color": 16753920
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Full Account Management section
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "title": "🧾 In-Training VAs: Full Account Management",
                "description": "Initial payment: **$349** ($174.50 upfront to begin).\n\n**Weeks 1 & 2:** Free service.\n**Week 3:** $144/week (24hr part-time) or $240/week (40hr full-time), continuing until canceled.\n**Week 4:** Weekly rate + remaining $174.50 initial fee.",
                "color": 16753920
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Bookkeeping section
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [
              {
                "title": "📚 In-Training VAs: Bookkeeping",
                "description": "Initial payment: **$349** ($174.50 upfront to begin).\n\n**Weeks 1 & 2:** Free service.\n**Week 3:** $96/week (24hr part-time) or $160/week (40hr full-time), continuing until canceled.\n**Week 4:** Weekly rate + remaining $174.50 initial fee.",
                "color": 16753920
              }
            ]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
